version: '2'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ".:/go/src/app"
    env_file: .env.development

  db:
    image: mysql:5.6
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
